### PR TITLE
[FR #125] Add asyncio support for memoize

### PR DESCRIPTION
**Pull request by i404788**
I've added the changes from the issue (https://github.com/grantjenks/python-diskcache/issues/125) & added a test (mirroring the regular memoize test).

### CODE REVIEW

**Comment by zoidbergwill** [comment]
Is this likely to get merged, if the PR is updated?

**Comment by grantjenks** [comment]
Also, this adds async support to memoize() in the core but there are several other places where decorators are available. Those should probably be changed too.

**Comment by i404788** [comment]
True, covering all of the decorator APIs with a near identical duplication of the code doesn't seem like a good idea. This is the 'simplest' solution, but it should be possible to make it something like:

```
@ft.wraps(func)
@autoasync(func)
async def wrapper(*args, **kwargs):
    ....
    result = await asyncify(func, *args, **kwargs)

```

The issue here is that the wrapper is always async; due to the keyword `async` not being a metaprogramming option (afaik). Attempts to convert between the two are pretty chaotic (See https://github.com/xloem/async_to_sync/blob/master/async_to_sync/__init__.py)

Maybe some `metaclass` with `__call__` would work but I don't think it will be pretty

**Comment by xloem** [comment]
> The issue here is that the wrapper is always async; due to the keyword `async` not being a metaprogramming option (afaik). Attempts to convert between the two are pretty chaotic (See https://github.com/xloem/async_to_sync/blob/master/async_to_sync/__init__.py)

note: I'm currently using `await asyncio.to_thread(sync_func)` and don't remember `async_to_sync` well.

**Pull request closed without merging**
