### PR TITLE
Adding memoizing decorator

### PR DESCRIPTION
**Pull request by tamirOK**
I just copied data from python3.5 lru_cache implementation and merged it with diskcache's cache.

### CODE REVIEW

**Comment by grantjenks** [comment]
This is a good start but the linked list isn't necessary. The cache will automatically evict as needed.

**Comment by grantjenks** [comment]
Some more thoughts:

1. How would separate processes use the same cache?
2. Probably better to use tempfile.mkdtemp rather than uuid
3. Better to use FanoutCache than Cache so we can suppress Timeout exceptions
4. I'm not sure the typed parameter is necessary. Their concern is hashing and equality but Cache doesn't use hashing and has a slightly different notion of equality that Python's ``__eq__``. I need to think about this more.

**Comment by tamirOK** [comment]
> This is a good start but the linked list isn't necessary. The cache will automatically evict as needed.

I have removed linked list from implementation. But I didn't understand how to store no more than max_size items in cache, so I removed that parameter too. Also I have added use_statistics flag for using builtin cache statistics. 



> How would separate processes use the same cache?

Currently I don't have a solution. I am still thinking about it.  I would be glad if you'd give me some hints.

> Probably better to use tempfile.mkdtemp rather than uuid

Done.

> Better to use FanoutCache than Cache so we can suppress Timeout exceptions

Done.

> I'm not sure the typed parameter is necessary. 

Removed this parameter.

**Comment by grantjenks** [comment]
Deployed at 2.8.2

**Pull request merged**
