### PR TITLE
Extract abstract class from Cache

### PR DESCRIPTION
**Pull request by thedrow**
This is in preparation for #188.

### CODE REVIEW

**Comment by grantjenks** [comment]
I don’t see the benefit of this change. Just use typical inheritance for #188

**Comment by thedrow** [comment]
It's easier to have the same interface automatically generated for you if you branch to a different class.

**Comment by grantjenks** [comment]
I don’t get what you mean.

**Comment by grantjenks** [comment]
To clarify, there's only one method in `Cache` that references `slite3.connect`. Inheriting that method and overriding it to use `rqlite` would seem sufficient to me.

**Pull request closed without merging**
