### PR TITLE
Add caveat about inconsistent pickles

### PR DESCRIPTION
**Pull request by grantjenks**
Add caveat about inconsistent pickles

### CODE REVIEW

**Comment by grantjenks** [comment]
Addresses #181

**Comment by jtrakk** [comment]
Hi, I'm trying to find a minimal example of inconsistent pickle results. Based on your experiment I thought this would show `False`, but it doesn't.

```py
import pickle


def f(*a, **kw):
    return pickle.dumps((a, kw))


val1 = pickle.dumps(f())


def f(*a, **kw):
    return pickle.dumps((a, kw))


val2 = pickle.dumps(f())

print(val1 == val2) # True
```

Do you happen to know what's required in order to see the inconsistent pickle output?

**Comment by grantjenks** [comment]
No, I haven’t debugged pickle to understand why. Try the example in #181

**Comment by grantjenks** [comment]
Superseded by b10b386

**Pull request closed without merging**
